name: CI Checks

on:
  push:

jobs:
  frontend-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      - name: Run Prettier
        working-directory: ./frontend
        run: npm run format:check

  backend-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run Ruff Checks
        working-directory: ./backend
        run: |
          uvx ruff check . --fix
          uvx ruff format .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.10"
          enable-cache: true

      - name: Install dependencies
        working-directory: ./backend
        run: uv sync --all-groups

      - name: Run pytest
        working-directory: ./backend
        run: PYTHONPATH=. uv run pytest
